[[headers]]
  for = "/pages/games/angrybirds/*.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/javascript"

[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/bare/*"
  to = "/static/uv/uv.handler.js"
  status = 200
  force = true
