[build]
  publish = "."

# Headers for JS files in other games
[[headers]]
  for = "/pages/games/angrybirds/*.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/javascript"

# Redirects for FNF Goose Mod game
[[redirects]]
  from = "/pages/games/fnf-goose-mod/*"
  to = "/pages/games/fnf-goose-mod/:splat"
  status = 200

# Trick to make absolute / paths inside FNF Goose Mod point to its folder
[[redirects]]
  from = "/fnf-goose-mod/*"
  to = "/pages/games/fnf-goose-mod/:splat"
  status = 200
  force = true
